version: "3.9"

services:
  db-news:
     image: postgres:15.2
     restart: always
     ports:
        - 5432:5432
     environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=news
     networks:
        - config_custom-app-network

  redis:
     image: redis:alpine
     restart: always
     ports:
        - 6379:6379
     networks:
        - config_custom-app-network

  app-news:
     build: ./
     ports:
        - 8080:8080
     networks:
        - config_custom-app-network
        
networks:
   config_custom-app-network:
      external: true
