version: "3.9"

services:
  db-news:
     image: postgres:15.2
     restart: always
     ports:
        - 5432:5432
     environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=news

  redis:
     image: redis:alpine
     restart: always
     ports:
        - 6379:6379

#  app-news:
#     build: ./
#     ports:
#        - 8080:8080