spring:
   profiles:
      active: dev
      
springdoc:
   show-actuator: false
   swagger-ui:
      enabled: true
                  
---

spring:
   config:
      activate:
         on-profile: dev

aspect:
   controllerLogging: disable
   caching:
      enable: false
      type: redis

connection:
   db:
      driverClassName: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://localhost:5432/news?charSet=utf-8
      username: admin
      password: admin
      maxPoolSize: 3
      connectionTimeout: 3000
   hibernate:
      schema: none
      sessionContext: thread
      dialect: org.hibernate.dialect.PostgreSQLDialect
      showSql: true
      transactionIsolationValue: 2
      

---      

spring:
   config:
      activate:
         on-profile: test
   cache:
      type: redis
   redis:
      host: localhost
      port: 6379

connection:
   db:
      driverClassName: org.postgresql.Driver
      jdbcUrl: ${db_url}
      username: ${db_user}
      password: ${db_password}
      maxPoolSize: 3
      connectionTimeout: 3000
   hibernate:
      schema: none
      sessionContext: thread
      dialect: org.hibernate.dialect.PostgreSQLDialect
      showSql: true
      transactionIsolationValue: 2
testcontainers:
   postgresqlDockerImage: postgres:15.2
   jdbcUrlEnvVar: db_url
   usernameEnvVar: db_user
   passwordEnvVar: db_password
   liquibaseChangelogFile: /liquibase/db-test-news-changelog.xml
         